# Generated by Django 4.2.25 on 2025-10-20 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_trip_group_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_instructions', models.TextField(default='Send payment screenshot to the bot.', help_text='Instructions shown to users for making payments')),
                ('support_contacts', models.TextField(blank=True, help_text='Contact information for user support')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
